<?php
return array(
    "main"=>array(
        "appName"=>"Medicus_System",
        "debugMode"=>true
    ),
    "db"=>array(
        "host"=>"127.0.0.1",
        "dbName"=>"medicusys",
        "user"=>"root",
        "pass"=>"",
        "charset"=>"utf8mb4"
    ),
    "csrfProtection"=>array(
        "enabled"=>true
    ),
    "api"=>array(
        "enabled"=>true,
        "versionCode"=>1,
        "token"=>"PUsecR0B6brOYUcrI9LhiXU8w5SlFRorlFrdrlV"
    )
);