<?php

namespace App\Models;

interface StatusCodes {
    const STATUS = [
        0 => 'PDO Exception',
        1 => 'Invalid E-Mail or password',
        2 => 'Invalid password.',
        3 => 'Invalid E-Mail',
        4 => 'Invalid first name',
        5 => 'Invalid last name',
        6 => 'Invalid patronymic',
        7 => 'Invalid birth date',
        8 => 'Invalid mobile phone number',
        9 => 'Invalid home address',
        10 => 'Invalid doctor',
        11 => 'Patient registered successfully',
        12 => 'Doctor registered successfully',
        13 => 'This E-Mail already exists',
        14 => 'This mobile phone already exists',
        15 => 'Password should be minimum 6 characters long.',
        16 => 'Invalid specialty',
        17 => 'User is already logged in',
        18 => 'Login successful',
        19 => 'Recorder registered successfully',
        20 => 'Unexpected error. Please contact server administrator.',
        21 => 'Please provide login and password.',
        22 => 'Invalid token',
        23 => 'Invalid user token',
        24 => 'Not signed in',
        25 => 'Not allowed',
        26 => 'Invalid page',
        27 => 'OK',
        28 => 'There was an error with getting information from the server',
        29 => 'Invalid gender id (Allowed: 1 = Male, 2 = Female)',
        30 => 'No access to the patient',
        31 => 'Invalid user id',
        32 => 'Invalid patient id',
        33 => 'Invalid gender',
        34 => 'Invalid symptoms',
        35 => 'Invalid language',
        36 => 'No possible diagnoses found',
        37 => 'Invalid diagnosis',
        38 => 'Unable to add diagnosis',
        39 => 'Unable to remove diagnosis',
        40 => 'Unable to edit diagnosis',
        41 => 'Unable to add recipe',
        42 => 'Unable to remove recipe',
        43 => 'Unable to edit recipe',
        44 => 'No access to diagnosis',
        45 => 'Invalid diagnosis id',
        46 => 'Invalid recipe',
        47 => 'Invalid da tales doses numero',
        48 => 'Invalid signa',
        49 => 'Unable to add recipe',
        50 => 'Unable to update recipe',
        51 => 'Invalid recipe id',
        52 => 'Unable to delete recipe',
        53 => 'User not found',
        54 => 'Invalid user_id or user_token',
        55 => 'Please provide user_id and user_token',
        56 => 'Invalid title',
        57 => 'Invalid message',
        58 => 'Message sent successfully',
        59 => 'Invalid FCM registration token',
        60 => 'Firebase error occurred',
        61 => 'FCM registration token updated successfully',
        62 => 'There was an error while updating FCM registration token'
    ];
}